file=["rishabh - meerut"
"imtiyaz - delhi"
"nilima - cochin"
"rati - shimla"
"ayishah - delhi"
"raghu - shimla"
"naseer - kanpur"
"karthikeyan - delhi"
"salma - jaipur"
"pankaj - delhi"
"brijesh - delhi"
"govind - delhi"
"puneet - shimla"
"siddhi - delhi"
"suman - jaipur"
"rajeev - shimla"
"mohinder - delhi"
"rajendra - jaipur"
"priyanka - shimla"
"neela - delhi"
"sashi - jaipur"
"sarika - delhi"
"deepti - shimla"
"harshad - delhi"
"trishna - raipur"
"pradeep - jaipur"
"sekhar - delhi"
"nand - delhi"
"anoop - delhi"
"balwinder - tokyo"]
names_file=open("save.text","w")
for names in file:
    names_file.write("" + names + "\n")
names_file.close()